### ISSUE TITLE
Creating relationships inside of an entity

### ISSUE THREAD

**Issue by bevbomb** [pepibumur/SugarRecord#197]
In SugarRecord prior to 2.1 Swift release, i used to have entities being mapped with a generic function and protocol and it used to access the current context by calling `self.context()` from within the entity when mapping to map relationships with other entities..
My problem seems to be that with the new release, contexts have been forced more so into the block of an operation which means if i have an Entity which has three seperate relationships, i'd have to map the first main entity then map all other relationships within the block..

When trying to use a single operation block to handle these functions and by passing the context to the mapping i receive the following error 

` *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Illegal attempt to establish a relationship 'author' between objects in different contexts`

**Comment by pepibumur** [comment]
@bevbomb I'm going to try to show you an example. It shouldn't be that difficult. The reaso why it forces doing operations in block is because it forces the developer towards good practises. When contexts are "free" to use, we end up messing up with their use and having problems accessing context in wrong threads. This is the example:

```swift
class PlaylistSaver: NSOperation {

  // MARK: - Attributes
  
  let store: CoreDataDefaultStorage
  let apiPlaylist: APIPlaylist
  let completion: (Playlist?, StoreError?) -> Void

  // MARK: - Init

  init(store: CoreDataDefaultStorage, apiPlaylist, APIPlaylist, completion: (Playlist?, StoreError?) -> Void) {
    self.store = store
    self.apiPlaylist = apiPlaylist
    self.completion = completion
  }

  // MARK: - NSOperation

  func main() {
    let playlistId: String = self.apiPlaylist.id
    store.operation { (context, save) in 
        // Save the playlist
        // Save its relationships (tracks) or find them in the database
        save()
    }
    dispatch_async(dispatch_get_main_queue()) {
      let playlist = try? store.fetch(Request<Playlist>().filteredWith("id", equalTo: playlistId))
      self.completion(playlist, nil)
    }
  }
}
```

1. The operation of saving your item is an operation, you can initialize it and enqueue it in an NSOperationQueue (to be executed in background)
2. The operation contains a completion block to report back the persisted entities in case you need them from UI. Although I'm reporting the playlist in this case it's not a good practise to use core data models directly, I recommend you to map them into an intermediate entity independent from the CoreData models.
3. Inside the closure you can do whatever you need, if the tracks of your playlist returned by the API are in the database you can find them and set the relationship manually. If they don't and they're contained in the playlist from the API you can create these models and set the relatinoship in the same block.

Try it and let me know if it helps.
Pedro

**Comment by wangshunping** [comment]
Helo , I didn't get the point about how to solve it .

I have two table in Sqlite3, one names Project and the other name Target.

many to one, One target map many project.

right now, i want to build a new project .

```
func newProject(controller: ProjectDetailViewController, didFinishAddingProjectName projectName: String) {
        // new  Project
        let targetObject = getTarget(self.target!.name)
        do {
            try! db!.operation { (context, save) throws -> Void in
                let newProject: Project = try! context.new()
                newProject.name = projectName
                newProject.target = targetObject
                try! context.insert(newProject)
                save()
            }
        }
        catch {
            // There was an error in the operation
            print("Oh on ... please kill me..")
        }
    }

```

i am an niewbie in swift , would please give me some help?

**Comment by wangshunping** [comment]
here is getProject

```
private func getTarget(targetName: String) -> Target {
        let target = try! db!.fetch(Request<Target>().filteredWith("name", equalTo: targetName)).first!
        return target
    }

```
