### ISSUE TITLE
Document how to assign relationships in an operation

### ISSUE THREAD

**Issue by jhoughjr** [pepibumur/SugarRecord#215]
I've been rewriting my code to use sugar record but have reached an impasse with
an error involving illegally setting a relationship on an object to an object from another context.
I don't see any examples in the example project or the documentation that deal with relationships.

It would seem, as in my case that this scenario would be creating a new entity in an operation, and then creating the relationship by setting an attribute on the created entity to an existing (previously fetched) entity.

I tried to do everything on the mainContext, but it doesn't appear to have a save method, and I still saw the error in the debugger, though it didn't crash.

**Comment by pepibumur** [comment]
@jhoughjr I don't think explaining how to set relationships is in the scope of the library documentation. That's part of how CoreData wok and its practices. SugarRecord encourages good practices but doesn't prevent you from understanding how CoreData works. Drop me a line if you have doubts.

**Comment by jhoughjr** [comment]
The issue could have been titled better, but I think the relevant part is "in an operation".
As the docs state that things that modify the DB should be done in an operation.
When in an operation to create a new entity, I can't work with relationships the normal way CoreData does, i.e. assign an entity or set of entities to the attribute of another entity.

None of the creation examples show this common scenario. 

A fetched entity doesn't exist in the context passed to the operation is the issue I'm seeing I think.
The readme does state that everything is propagated to all available contexts so I don't know what I'm missing. The entity I previously fetched, which was already saved isn't in the context passed to the operation.

That is why I requested documentation.

**Comment by pepibumur** [comment]
@jhoughjr when the operation is created it gets a fresh context, so if you're not doing saving operations in the main thread you should get a fresh data state. The idea is keeping operations atomic and don't retain contexts. Could you share an example of what you mentioned? I'll help you with it.

**Comment by jhoughjr** [comment]
Thanks! Here is a gist of the relevant parts https://gist.github.com/jhoughjr/b166034a5d26d3d2f3a3

**Comment by v-ken** [comment]
I think this is a completely relevant request from OP for relationship assignments to be documented. I completely understand how core data works and have been using it in all my projects. However, I'm also facing the same roadblocks as OP when trying to use SugarRecord. The reason that understanding CoreData alone is not sufficient is due to the fact that contexts seems to be used differently in SugarRecord (`db.operation` instead). E.g. What is the equivalent of `context.performBlock()` + `context.objectWithID()` when trying to get the object in the same context for a relationship assignment in the SugarRecord style?
  
Something like a "SugarRecord best practice when dealing with relationships" topic would be great to have! =)

**Comment by doodzik** [comment]
Can this issue be reopened?
